### ISSUE TITLE
Some FastPass components missing font-weights in mac/linux

### ISSUE THREAD

**Issue by dbjorge** [microsoft/accessibility-insights-web#5131]
## Describe the bug

During 2.30.1 insider testing, we found that several UI components used in different parts of FastPass were using `font-weight` styles implied by default browser user agent CSS instead of explicitly specifying font-weights (ideally by using the named style includes from `fonts.scss`). These cases happened to end up with correct font weights on Windows' default user agent sheets, but end up with incorrect font weights in Chrome/Chromium on Mac and Linux; some cases are under-weighted and some are over-weighted.

Specific cases:

* [ ] Details View > Fast Pass > Automated Checks > Rule IDs inside of the collapsible controls should be weight 600
* [ ] Details View > Fast Pass > Automated Checks > Collapsible rule content > "More resources for this rule" header should be weight 600
* [ ] Details View > Fast Pass > Automated Checks > Collapsible rule content > Cards' row labels (eg, "Path", "Snippet") should be weight 600
* [ ] Details View > Fast Pass > Tab stops > Failed instances section > Requirement names inside of the collapsible controls should be weight 600
* [ ] Exported Fast Pass report > Failed instances section > Same 3 issues as the Details View Automated Checks section
* [ ] Exported Fast Pass report > Passed or Incomplete checks sections > Rule/requirement names inside of the collapsible controls should be weight 600 

**To Reproduce**

1. Use Mac or Linux (tested on macOS 11.4 with Chrome Beta 98 and Stable 97, as well as Ubuntu 20.04 with Chromium stable 97)
2. Open any website with violations (eg, [w3 city lights](https://www.w3.org/WAI/demos/bad/before/home.html))
3. Start a FastPass
4. Go to Automated Checks and expand a card view
5. Observe incorrect font weights on requirement names, "More resources for this rule", and card row labels
6. Go to Tab Stops, mark a requirement as failed, and add an instance
7. Observe incorrect font weight on collapsible requirement names in the instance list control
8. Export a FastPass report and open it
9. Expand a "Failed" instance
10. Observe incorrect font weight on requirement names, "More resources for this rule", and card row labels
11. Expand a "Passed" or "Incomplete" checks section
12. Observe incorrect font weight on requirement names

## CodePen repro example

n/a

## Expected behavior

Font weights should match the behavior on Windows (the components in question should be updated to specify explicit `font-weights` by including the font style mixins defined in `fonts.scss`)

## Screenshots

![screenshot highlighting issues in Details View automated checks](https://user-images.githubusercontent.com/376284/151888022-dc61a33f-7679-4815-b658-fc0e9204c092.png)
![screenshot highlighting issues in Details View tab stops](https://user-images.githubusercontent.com/376284/151888070-7f4b994e-9784-4021-b1ab-60f68f09f4ed.png)
![screenshot highlighting issues in FastPass report failed instances](https://user-images.githubusercontent.com/376284/151888176-890543b1-fd13-4708-97ee-d5066ee21216.png)
![screenshot highlighting issues in FastPass report passed checks](https://user-images.githubusercontent.com/376284/151888134-649e12f6-6392-4f79-a384-7e9f52339afb.png)

**TODO**

## Context (please complete the following information)

- OS Name & Version: Tested on Mac 11.4 and Ubuntu 20.04
- AI-Web Version & Environment: Tested on 2.30.1 Insider and 2.29.0 Production
- Browser Version: Tested on Chrome 98.0.4758.74 beta, Chromium 97.0.46.92.99 stable
- Target Page: Any page with FastPass violations (eg, [w3 city lights](https://www.w3.org/WAI/demos/bad/before/home.html))

## Are you willing to submit a PR?

yes

## Did you search for similar existing issues?

yes

## Additional context

n/a

**Comment by dbjorge** [comment]
LGTM in canary on my Ubuntu and MacOS machines!
